# Generated by Django 3.1.1 on 2020-09-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtusa_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_desc', models.CharField(max_length=200)),
                ('product_price', models.CharField(max_length=200)),
                ('product_type', models.CharField(max_length=200)),
            ],
        ),
    ]
